# see: https://gohugo.io/getting-started/configuration/

baseURL      = "https://astronoka.github.io" # Hostname (and path) to the root.
title        = "Astronoka Archive" # Site title.
theme        = "coder" # Set the theme.
languageCode = "ja-JP" # The site’s language code.

paginate     = 20 # Default number of pages per page in pagination.
canonifyurls = true # Enable to turn relative URLs into absolute.

pygmentsstyle                 = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences            = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.

[params] # theme parameters
    author      = "astronoka"                    # Author's name.
    info        = "the manuscripts of astronoka" # Author's job title or info.
    description = "the manuscripts of astronoka" # Site description.
    keywords    = "blog,developer,personal"      # Site keywords.

    #disqusShortname = "yourdiscussshortname" # Enable or disable Disqus

    # Whether you want to hide copyright and credits in the footer.
    hideCredits   = false
    hideCopyright = false

    # Custom CSS
	custom_css = []

# Social links
[[params.social]]
    name   = "Github"
    weight = 1
    url    = "https://github.com/astronoka/"
#[[params.social]]
#    name   = "Twitter"
#    weight = 2
#    url    = "https://twitter.com/johndoe/"
#[[params.social]]
#    name   = "LinkedIn"
#    weight = 3
#    url    = "https://www.linkedin.com/in/johndoe/"

# Menu links
[[menu.main]]
    name = "Posts"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
